### PR TITLE
Fix failing room 2.5.0 instrumentation

### LINKED ISSUE #434: Sentry causes `java.lang.NoSuchFieldError: No instance field mDelegate` with Room 2.5.0
### Integration

sentry-android

### Build System

Gradle

### AGP Version

7.4.0

### Proguard

Enabled

### Version

probably latest (automatically added through io.sentry.android.gradle 3.2.0 or 3.4.1))

### Steps to Reproduce

1. Add Sentry to an Android app with Room 2.5.0
2. Insert something into the database

### Expected Result

Something is stored in the database/no exceptions

### Actual Result

```
java.lang.NoSuchFieldError: No instance field mDelegate of type Landroid/database/sqlite/SQLiteStatement; in class Landroidx/sqlite/db/framework/FrameworkSQLiteStatement; or its superclasses (declaration of 'androidx.sqlite.db.framework.FrameworkSQLiteStatement' appears in /data/app/~~pAvZq98N6TMS64i4kOmPzw==/de.visualvest.pushtan.app-sGrKnNFuWTsxX0Le4FBKJg==/base.apk!classes14.dex)
at androidx.sqlite.db.framework.FrameworkSQLiteStatement.executeInsert(Unknown Source:4)
at androidx.room.EntityInsertionAdapter.insert(EntityInsertionAdapter.kt:68)
``` 

Details see https://issuetracker.google.com/issues/265824784
Sentry seems to override the SQlite version

### PR DESCRIPTION
**Pull request by markushi**
## :scroll: Description
Due to the recent `2.3.0` release of `androidx.sqlite:sqlite-framework:2.3.0`([link]( https://developer.android.com/jetpack/androidx/releases/sqlite#version_230_3)) which is used by room `2.5.0` our bytecode instrumentation fails and causes a runtime crash.

## :bulb: Motivation and Context
Fixes #434

## :green_heart: How did you test it?
Sadly just some manual testing, ideally we can have automated tests for this and make the instrumentation itself more stable, any input welcome!

## :pencil: Checklist

- [x] I reviewed the submitted code
- [x] I added tests to verify the changes
- [x] I updated the docs if needed
- [x] No breaking changes

### CODE REVIEW

**Comment by markushi** [comment]
Please ignore the typo in the branch name 🙈

File: plugin-build/src/main/kotlin/io/sentry/android/gradle/instrumentation/androidx/sqlite/statement/visitor/ExecuteStatementMethodVisitor.kt [hunk 1]
```diff
@@ -105,16 +107,17 @@ class ExecuteStatementMethodVisitor(
...
 
     /*
-    String description = mDelegate.toString();
+    String description = delegate.toString();
     int index = description.indexOf(':');
     description = description.substring(index + 2);
      */
     private fun MethodVisitor.visitExtractDescription() {
         visitVarInsn(ALOAD, 0) // this
+        val name = if (androidXSqliteVersion >= SemVer(2, 3, 0)) "delegate" else "mDelegate"
```
Comment (romtsn) [inline plugin-build/src/main/kotlin/io/sentry/android/gradle/instrumentation/androidx/sqlite/statement/visitor/ExecuteStatementMethodVisitor.kt:116]:
```suggestion
        // androidx.sqlite changed the name of the variable in version 2.3.0
        val name = if (androidXSqliteVersion >= SemVer(2, 3, 0)) "delegate" else "mDelegate"
```

File: plugin-build/src/main/kotlin/io/sentry/android/gradle/util/SentryAndroidSdkChecker.kt [hunk 2]
```diff
@@ -3,6 +3,7 @@ package io.sentry.android.gradle.util
 import io.sentry.android.gradle.services.SentryModulesService
 import org.gradle.api.Project
```
Comment (romtsn) [inline plugin-build/src/main/kotlin/io/sentry/android/gradle/util/SentryAndroidSdkChecker.kt:4]: `l`: Maybe rename the class to something like `SentryModulesCollector`?

Comment (romtsn) [reply plugin-build/src/main/kotlin/io/sentry/android/gradle/util/SentryAndroidSdkChecker.kt:4]: The function name we could rename from `detectSentryAndroidSdk` to something like `collectModules` or so?

File: plugin-build/src/main/kotlin/io/sentry/android/gradle/util/SentryAndroidSdkChecker.kt [hunk 3]
```diff
@@ -18,35 +19,46 @@ fun Project.detectSentryAndroidSdk(
...
 
     configProvider.configure { configuration ->
         configuration.incoming.afterResolve {
-            val sentryModules = it.resolutionResult.allComponents.filterSentryModules(logger)
+            val allModules = it.resolutionResult.allComponents.versionMap(logger)
+            val sentryModules = allModules.filter { (identifier, _) ->
+                identifier.group == "io.sentry"
+            }.toMap()
+
+            val externalModules = allModules.filter { (identifier, _) ->
```
Comment (romtsn) [inline plugin-build/src/main/kotlin/io/sentry/android/gradle/util/SentryAndroidSdkChecker.kt:34]: `m`: Maybe worth adding a quick integration test, that adds `androidx.sqlite:sqlite-framework` to the dependencies of a fixture, and then check that it's in the `externalModules` of the `SentryModulesService`? Similar to what we do for testing that sentry modules are there (`SentryAndroidSdkCheckerTest`)

**Review by romtsn — APPROVED** [review]
Very nice, thanks for taking care of this 🚀 

For the better futureproof solution I've updated #401
