### PR TITLE
Fix: Ignore R8 minified libs from instrumentation

### LINKED ISSUE #315: Sentry Plugin is causing the application to crash
### Gradle Version

7.4.2

### AGP Version

7.1.2

### Code Minifier/Optimizer

Proguard

### Version

3.0.0

### Sentry SDK Version

5.7.1

### Description

We are using [Braze](https://github.com/Appboy/appboy-android-sdk) library in our application and it works fine.
If we apply Sentry plugin, the application crashes when opening.

### Steps to Reproduce

You can reproduce the error with the repository given below:
https://github.com/dorukkangal/braze-sample

The error doesn't occur again when I disable `tracingInstrumentation`.
I think the bytecode manipulation is causing VerifyError.

### Log

```shell
java.lang.VerifyError: Verifier rejected class com.braze.support.BrazeImageUtils: android.graphics.Bitmap com.braze.support.BrazeImageUtils.getLocalBitmap(android.net.Uri, int, int) failed to verify: android.graphics.Bitmap com.braze.support.BrazeImageUtils.getLocalBitmap(android.net.Uri, int, int): [0x75] register v6 has type Precise Reference: java.lang.String but expected Reference: java.io.FileInputStream (declaration of 'com.braze.support.BrazeImageUtils' appears in /data/app/~~mudJ3b4VR55TXuQMIoS8ew==/com.hepsiburada.merchant.qa-oFX-w_fRWgtmWrKbDRq6yg==/base.apk)
        at com.braze.support.BrazeImageUtils.getImageLoaderCacheSize(SourceFile:1)
        at com.braze.images.DefaultBrazeImageLoader.<init>(SourceFile:4)
        at com.appboy.Appboy.<init>(SourceFile:59)
        at com.braze.Braze.<init>(SourceFile:1)
        at com.appboy.Appboy.getInstance(SourceFile:7)
        at com.hepsiburada.merchant.di.AppModule.provideBraze(AppModule.kt:46)
        at com.hepsiburada.merchant.di.AppModule_ProvideBrazeFactory.provideBraze(AppModule_ProvideBrazeFactory.java:41)
        at com.hepsiburada.merchant.core.DaggerApp_HiltComponents_SingletonC$SwitchingProvider.get0(DaggerApp_HiltComponents_SingletonC.java:2011)
        at com.hepsiburada.merchant.core.DaggerApp_HiltComponents_SingletonC$SwitchingProvider.get(DaggerApp_HiltComponents_SingletonC.java:2354)
        at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
        at com.hepsiburada.merchant.core.DaggerApp_HiltComponents_SingletonC$SwitchingProvider.get0(DaggerApp_HiltComponents_SingletonC.java:2008)
        at com.hepsiburada.merchant.core.DaggerApp_HiltComponents_SingletonC$SwitchingProvider.get(DaggerApp_HiltComponents_SingletonC.java:2354)
        at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
        at com.hepsiburada.merchant.core.DaggerApp_HiltComponents_SingletonC$SwitchingProvider.get0(DaggerApp_HiltComponents_SingletonC.java:1993)
        at com.hepsiburada.merchant.core.DaggerApp_HiltComponents_SingletonC$SwitchingProvider.get(DaggerApp_HiltComponents_SingletonC.java:2354)
        at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
        at com.hepsiburada.merchant.core.DaggerApp_HiltComponents_SingletonC$ActivityCImpl.injectMainActivity2(DaggerApp_HiltComponents_SingletonC.java:1506)
        at com.hepsiburada.merchant.core.DaggerApp_HiltComponents_SingletonC$ActivityCImpl.injectMainActivity(DaggerApp_HiltComponents_SingletonC.java:1474)
        at com.hepsiburada.merchant.ui.Hilt_MainActivity.inject(Hilt_MainActivity.java:66)
        at com.hepsiburada.merchant.ui.Hilt_MainActivity$1.onContextAvailable(Hilt_MainActivity.java:37)
        at androidx.activity.contextaware.ContextAwareHelper.dispatchOnContextAvailable(ContextAwareHelper.java:99)
        at androidx.activity.ComponentActivity.onCreate(ComponentActivity.java:313)
        at androidx.fragment.app.FragmentActivity.onCreate(FragmentActivity.java:249)
        at com.hepsiburada.merchant.utils.base.BaseActivity.onCreate(BaseActivity.kt:30)
        at com.hepsiburada.merchant.ui.MainActivity.onCreate(MainActivity.kt:69)
        at android.app.Activity.performCreate(Activity.java:8054)
        at android.app.Activity.performCreate(Activity.java:8034)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1341)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3666)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3842)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2252)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7842)
        at java.lang.reflect.Method.invoke(Native Method)
```

### PR DESCRIPTION
**Pull request by romtsn**
## :scroll: Description

Ignore R8-minified libs from instrumentation by looking at the constant pool of a .class file and search for the R8 marker. This uses a lot of reflection, but should be fine because it's done on JVM and not Android. Still, I filed an issue on AGP's tracker, maybe they provide and API for that, so we can avoid reflection.

## :bulb: Motivation and Context

Closes #315 

## :green_heart: How did you test it?
Manually on a sample project and automatically

## :pencil: Checklist

- [x] I reviewed the submitted code
- [x] I added tests to verify the changes
- [ ] I updated the docs if needed
- [x] No breaking changes

### CODE REVIEW

File: plugin-build/src/main/kotlin/io/sentry/android/gradle/instrumentation/util/ConstantPoolHelpers.kt [hunk 1]
```diff
@@ -0,0 +1,86 @@
...
+    val charBuffer = CharArray(maxStringLength)
+    // R8 marker is usually in the first 3-5 entries, so we limit it at 10 to speed it up
+    // (constant pool size can be huge otherwise)
+    val poolSize = minOf(10, itemCount)
+    for (i in 1 until poolSize) {
+        try {
+            val constantPoolEntry = readConst(i, charBuffer)
+            if (constantPoolEntry is String && "~~R8" in constantPoolEntry) {
+                // ~~R8 is a marker in the class' constant pool, which r8 itself is looking at when
+                // parsing a .class file. See here -> https://r8.googlesource.com/r8/+/refs/heads/main/src/main/java/com/android/tools/r8/dex/Marker.java#53
```
Comment (marandaneto) [inline plugin-build/src/main/kotlin/io/sentry/android/gradle/instrumentation/util/ConstantPoolHelpers.kt:60]: What if its minified by proguard or dexguard?

Comment (romtsn) [reply plugin-build/src/main/kotlin/io/sentry/android/gradle/instrumentation/util/ConstantPoolHelpers.kt:60]: dexguard only works for android apps afaik, so not possible to minify libs. + Our license has expired, so I have no way to test it :)

just checked with proguard - there's no marker or anything in the constant pool saying it was minified with proguard. 

But I'll double-check with the guardsquare guys, I think I can reach them somewhere.

Comment (marandaneto) [reply plugin-build/src/main/kotlin/io/sentry/android/gradle/instrumentation/util/ConstantPoolHelpers.kt:60]: @romtsn thanks.
So if you are using proguard, do the unit tests break with minified libs?

Comment (romtsn) [reply plugin-build/src/main/kotlin/io/sentry/android/gradle/instrumentation/util/ConstantPoolHelpers.kt:60]: so far - nope, I think `gms` and `google-play-services` are still minified with proguard and not R8 (because they also don't have any marker in there), but for those our fixes are working fine so far.

I think going forward we should still introduce the `excludes` option so people can manually excluded those classes that fail without us needing to bugfix everytime. I think with this change we cover a good portion of minified libs already

**Review by marandaneto — APPROVED** [review]
